# Generated by Django 5.1.4 on 2024-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_products_id_alter_products_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductCode',
            field=models.CharField(max_length=255),
        ),
    ]
